[font]
normal = { family = "Orbit", style = "Regular" }

[general]
import = [
    "~/.config/alacritty/themes/themes/carbonfox.toml"
]

[terminal]
shell.program = "/usr/bin/fish"

[window]
opacity = 0.9

